### ISSUE TITLE
acts_as_paranoid not working with rails 7.2 when this gem is installed

### ISSUE THREAD

**Issue by navidemad** [Faveod/arel-extensions#114]
Follow up of https://github.com/ActsAsParanoid/acts_as_paranoid/issues/345

Create a file called bug.rb with the following content and run it as `ruby bug.rb`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "pg", "1.5.7"

  # It is working with this version
  # gem "activerecord", "7.1.3.4", require: false
  # It is not working with this version
  gem "activerecord", "7.2.0", require: false
  gem "acts_as_paranoid", "0.10.2", require: false
  gem "arel_extensions", "2.1.11", require: false
end

require "active_record"
require "arel_extensions"

ActiveRecord::Schema.verbose = false
ActiveRecord::Base.logger = nil
ActiveRecord::Base.then do |base|
  base.establish_connection(adapter: "postgresql", host: "localhost", database: "postgres")
  begin
    base.connection.create_database("acts_as_paranoid_bug_report")
  rescue ActiveRecord::DatabaseAlreadyExists
    base.connection.drop_database("acts_as_paranoid_bug_report")
    base.connection.create_database("acts_as_paranoid_bug_report")
  end
  base.establish_connection(adapter: "postgresql", host: "localhost", database: "acts_as_paranoid_bug_report")
end

ActiveRecord::Schema.define do
  create_table :parkings, force: true do |t|
    t.string :name, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :parkings, :deleted_at

  create_table :spots, force: true do |t|
    t.integer :parking_id, null: false
    t.string :number, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :spots, :parking_id
  add_index :spots, :deleted_at
end

ActiveRecord::Base.logger = Logger.new($stdout)

require "acts_as_paranoid"
require "minitest/autorun"

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Parking < ApplicationRecord
  acts_as_paranoid
  has_many :spots, dependent: :destroy
end

class Spot < ApplicationRecord
  acts_as_paranoid
  belongs_to :parking
end

class BugTest < Minitest::Test
  def setup
    parking = Parking.create!(name: "Foo")
    parking.spots.create!(number: "42")
  end

  def test_output_has_many_relation
    puts ("#" * 100) + Parking.last.spots.to_sql
    assert Parking.last.spots.to_sql.include?("\"spots\".\"deleted_at\" IS NULL")
  end
end
```

**Comment by stackmystack** [comment]
Hi @navidemad, thanks for the bug report.

I tried to get back as far as [v2.0.15](https://rubygems.org/gems/arel_extensions/versions/2.0.15) from December 14, 2020, and the code still breaks.

I've been looking deeper into the problem, and my initial conclusion is that it's no fault of arel_extension. There's something that changed in `ActiveRecord` that's causing all of this, and I am not sure the fix needs to come from us.

Regardless, I will continue to look into it, but the maintainers of `acts_as_paranoid` should do so in parallel. I think they're playing with the definition of an `ActiveRecord` and `Relation`, and your issue comes from that.

More specifically, when looking at to_sql, the issue is in [`activerecord/lib/active_record/relation.rb`](https://github.com/rails/rails/blob/3ae6284f0e4f252429210e469b2129a84495612e/activerecord/lib/active_record/relation.rb#L1196), where `arel` is already wrong and doesn't contain `deleted_at`.

**Comment by stackmystack** [comment]
@navidemad let's pick up the conversation from where it stopped on acts_as_paranoid. Please let me know when you get the chance to validate the patch.

I have https://github.com/Faveod/arel-extensions/pull/115 waiting for merger. I can release soon after.

**Comment by navidemad** [comment]
@stackmystack I tried your patch version, it works but something weird the version of the arel_extensions is 1.4.0

With:
`gem "arel_extensions" # Arel Extensions adds shortcuts, fixes and new ORM mappings (Ruby to SQL) to Arel`
I am getting:
```sh
bundle update
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using arel_extensions 2.1.11 (was 1.4.0)
```

When i switch to your patch PR:
`gem "arel_extensions", github: "stackmystack/arel-extensions", branch: "rails-7.2"`
I am getting:
```sh
Fetching https://github.com/stackmystack/arel-extensions.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using arel_extensions 1.4.0 (was 2.1.11) from https://github.com/stackmystack/arel-extensions.git (at rails-7.2@40cf5dc)
Bundle updated!
```

**Comment by stackmystack** [comment]
>     * It appears that the gem version downgrades from **2.1.11** to **1.4.0** when switching to your patch.
>
>     * Is this the expected behavior?

Yes, absolutely expected. We bundle 2 versions, the `1.*` is for `rails < 6`, and `2.*` is for `rails >= 6`.
When you download the gem from rubygems.org, we make sure to bundle those separate versions correctly.
When you pull from git, we don't have everything set in place correctly for the proper version numbering.

>     * Should not the patch be based on the latest version of the gem?

It is, it's just displaying the wrong version number for the reason mentioned above.

> I tested your patch, and it works

Thanks a lot. I will merge and release asap.

**Comment by stackmystack** [comment]
@navidemad v2.2.0 was released on rubygems.org
