### ISSUE TITLE
presence or coalesce_blank

### ISSUE THREAD

**Issue by akimd** [Faveod/arel-extensions#13]
I have had to written something like this:

```ruby
Arel.when(at[:foo].blank).then(at[:bar]).else(at[:foo"])
```

except that `foo` and `bar` are much trickier to write.  This makes the construct harder to read than needed.  I would prefer to write something like

```ruby
at[:foo].coalesce_blank(at[:bar])
```

or maybe

```ruby
at[:foo].presence.coalesce(at[:bar])
```

where `presence` maps blanks to null.

Cheers!

**Comment by stackmystack** [comment]
Finally addressed in [PR#90](https://github.com/Faveod/arel-extensions/pull/90)
