### ISSUE TITLE
bundle update fails for 2.0.5

### ISSUE THREAD

**Issue by joshleblanc** [Faveod/arel-extensions#23]
```
Gem::Package::PathError: installing into parent path
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/.codeclimate.yml of
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/arel_extensions-2.0.5 is not allowed
An error occurred while installing arel_extensions (2.0.5), and
Bundler cannot continue.
```

**Comment by jdelporte** [comment]
Thanks for the quick notification. It appeared that the gem locally built worked just fine but not from rubygems.
the newly pushed version 2.0.6 works just fine.

**Comment by jdelporte** [comment]
It seems there is another issue with this version too. We invite you to go back to a previous version before we release a stable one.
