### ISSUE TITLE
undefined method `val' for #<Arel::Nodes::Casted:0x0000561fe1143398>

### ISSUE THREAD

**Issue by dannyvanhoof** [Faveod/arel-extensions#40]
We ran into a problem in combination with ransack. After debugging it turns out that this is related to:

```
class Arel::Nodes::Casted
  include Arel::AliasPredication

  # They forget to define hash.
  def hash
    [self.class, self.val, self.attribute].hash
  end
end
```

it looks as if `self.val` needs to be `self.value`?

Now, I also see that in your development code you already added 

`if Gem::Version.new(Arel::VERSION) < Gem::Version.new("10.0.0")`

which also fixes the issue.

It is possible to release this as it stops us from going to Rails 6.1?

**Comment by jdelporte** [comment]
Hi,
v2.0.16 including the correction you are referring to is available on rubygems.

**Comment by dannyvanhoof** [comment]
@jdelporte This is, I must say, the fastest fix I've ever seen!  Thanks!
