### ISSUE TITLE
concat result of substring with string fails

### ISSUE THREAD

**Issue by scambra** [Faveod/arel-extensions#6]
(Model.arel_table[:column].substring(1,4) + '0').to_sql fails with error RuntimeError: unsupported: String

I would expect to return (using Mysql):
"CONCAT(SUBSTRING(`entities`.`ledger_account`, 1, 4), '0')"

**Comment by scambra** [comment]
Also, concat result of 2 substring functions is wrong:
column = Model.arel_table[:column]
(column.substring(1,4) + column.substring(6)).to_sql
"(SUBSTRING(`entities`.`ledger_account`, 1, 4) + SUBSTRING(`entities`.`ledger_account`, 6))"

It should use concat in mysql:
"CONCAT(SUBSTRING(`entities`.`ledger_account`, 1, 4), SUBSTRING(`entities`.`ledger_account`, 6))"

**Comment by jdelporte** [comment]
Thanks you for reporting this issue and helping us improving this gem. We'll fix this for the next version.
In the mean time, you can still use the `ArelExtensions::Nodes::Concat` initializer method to perform the concat.
Regards

**Comment by scambra** [comment]
Thanks. It's a great gem, my code is much cleaner now
