### ISSUE TITLE
unable to bundle update with arel-extensions 1.6.0

### ISSUE THREAD

**Issue by roscom** [Faveod/arel-extensions#8]
Using rails 4.2.10

I note that the requirements for including arel-extensions are: Arel 6 (Rails 4) or Arel 7+ (Rails 5).
prior to including arel-extensions in the Gemfile, arel was shown in the Gemfile.lock as:

> 42       activerecord (>= 3.2, < 6.0)
> 43       rake (>= 10.4, < 13.0)
> 44     **arel (6.0.4)**
> 45     attr_encrypted (3.1.0)
> 46       encryptor (~> 3.0.0)
> 47     autoprefixer-rails (9.3.1)

We have arel 6.0.4.

So Gemfile amended to include:

```
ruby '2.5.1'
gem 'rails', '= 4.2.10'
 .
 .
 .
gem 'arel-extensions', require: 'arel/extensions'
 .
etc
```

in the Gemfile

and ran bundle update, which resulted in many failures, including:
```
Bundler could not find compatible versions for gem "arel":
  In Gemfile:
    rails (= 4.2.10) was resolved to 4.2.10, which depends on
      activerecord (= 4.2.10) was resolved to 4.2.10, which depends on
        arel (~> 6.0)

    arel-extensions was resolved to 1.5.2, which depends on
      arel (>= 7.0.0)
```
which seems to suggest that arel 6 might not be supported.

Could you please confirm, or, suggest a way to install against arel 6.

Thank you.

**Comment by jdelporte** [comment]
As it is rubygems which manages dependencies I think you are trying to install a different gem ([https://github.com/malomalo/arel-extensions](url) which requires arel 7). 

The gem we develop can be found here [https://rubygems.org/gems/arel_extensions](url) and can be install againt arel 6.

Let us know if you encounter any issue or if you want to provide any feedback.

Regards.
